/*
 * Copyright 2023 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

export const expectedAuditResult = [
  {
    url: 'https://www.adobe.com/',
    pageviews: '36064271',
    avgcls: 0.148,
    avginp: 65,
    avglcp: 5239,
  },
  {
    url: 'https://www.adobe.com/express/feature/image/remove-background',
    pageviews: '2737380',
    avgcls: 0.129,
    avginp: 95,
    avglcp: 1423,
  },
  {
    url: 'https://www.adobe.com/express/',
    pageviews: '2703493',
    avgcls: 0.028,
    avginp: 79,
    avglcp: 1869,
  },
];
export const rumData = {
  ':names': [
    'results',
    'meta',
  ],
  ':type': 'multi-sheet',
  ':version': 3,
  results: {
    limit: 6,
    offset: 1,
    total: 6,
    data: [
      {
        url: 'https://www.adobe.com/',
        pageviews: '36064271',
        pageviews_1: '3549602',
        pageviews_diff: '32514669',
        lcpgood: 32,
        fidgood: 88,
        inpgood: 82,
        clsgood: 60,
        lcpbad: 37,
        fidbad: 0,
        inpbad: 0,
        clsbad: 18,
        avglcp: 5239,
        avgfid: 6,
        avginp: 65,
        avgcls: 0.148,
        rumshare: '43.455607462',
        lcpgood_1: 25,
        fidgood_1: 89,
        inpgood_1: 83,
        clsgood_1: 89,
        lcpbad_1: 45,
        fidbad_1: 1,
        inpbad_1: 3,
        clsbad_1: 0,
        avglcp_1: 6376,
        avgfid_1: 7,
        avginp_1: 72,
        avgcls_1: 0.01,
        rumshare_1: '6.99597117',
        url_1: 'https://www.adobe.com/',
      },
      {
        url: 'https://www.adobe.com/express/feature/image/remove-background',
        pageviews: '2737380',
        pageviews_1: '2246720',
        pageviews_diff: '490660',
        lcpgood: 80,
        fidgood: 87,
        inpgood: 82,
        clsgood: 55,
        lcpbad: 4,
        fidbad: 1,
        inpbad: 0,
        clsbad: 20,
        avglcp: 1423,
        avgfid: 10,
        avginp: 95,
        avgcls: 0.129,
        rumshare: '3.298403308',
        lcpgood_1: 81,
        fidgood_1: 87,
        inpgood_1: 78,
        clsgood_1: 44,
        lcpbad_1: 4,
        fidbad_1: 1,
        inpbad_1: 4,
        clsbad_1: 33,
        avglcp_1: 1452,
        avgfid_1: 12,
        avginp_1: 116,
        avgcls_1: 0.774,
        rumshare_1: '4.428098797',
        url_1: 'https://www.adobe.com/express/feature/image/remove-background',
      },
      {
        url: 'https://www.adobe.com/express/',
        pageviews: '2703493',
        pageviews_1: '2996880',
        pageviews_diff: '-293387',
        lcpgood: 73,
        fidgood: 87,
        inpgood: 83,
        clsgood: 80,
        lcpbad: 7,
        fidbad: 1,
        inpbad: 0,
        clsbad: 3,
        avglcp: 1869,
        avgfid: 8,
        avginp: 79,
        avgcls: 0.028,
        rumshare: '3.257571201',
        lcpgood_1: 76,
        fidgood_1: 88,
        inpgood_1: 84,
        clsgood_1: 84,
        lcpbad_1: 6,
        fidbad_1: 1,
        inpbad_1: 2,
        clsbad_1: 1,
        avglcp_1: 1718,
        avgfid_1: 8,
        avginp_1: 73,
        avgcls_1: 0.029,
        rumshare_1: '5.906601945',
        url_1: 'https://www.adobe.com/express/',
      },
      {
        url: 'https://www.adobe.com/acrobat/online/pdf-to-word.html',
        pageviews: '6999',
        pageviews_1: '1663400',
        pageviews_diff: '-301000',
        lcpgood: 58,
        fidgood: 98,
        inpgood: 86,
        clsgood: 47,
        lcpbad: 30,
        fidbad: 1,
        inpbad: 0,
        clsbad: 36,
        avglcp: 5086,
        avgfid: 5,
        avginp: 112,
        avgcls: 0.686,
        rumshare: '1.641622525',
        lcpgood_1: 59,
        fidgood_1: 98,
        inpgood_1: 87,
        clsgood_1: 46,
        lcpbad_1: 30,
        fidbad_1: 1,
        inpbad_1: 7,
        clsbad_1: 36,
        avglcp_1: 5332,
        avgfid_1: 5,
        avginp_1: 112,
        avgcls_1: 0.69,
        rumshare_1: '3.278423452',
        url_1: 'https://www.adobe.com/acrobat/online/pdf-to-word.html',
      },
      {
        url: 'https://www.adobe.com/acrobat/online/merge-pdf.html',
        pageviews: '1',
        pageviews_1: '818200',
        pageviews_diff: '-134300',
        lcpgood: 81,
        fidgood: 98,
        inpgood: 83,
        clsgood: 55,
        lcpbad: 11,
        fidbad: 1,
        inpbad: 0,
        clsbad: 29,
        avglcp: 2120,
        avgfid: 5,
        avginp: 144,
        avgcls: 0.412,
        rumshare: '0.824064625',
        lcpgood_1: 81,
        fidgood_1: 98,
        inpgood_1: 82,
        clsgood_1: 46,
        lcpbad_1: 10,
        fidbad_1: 1,
        inpbad_1: 9,
        clsbad_1: 42,
        avglcp_1: 2056,
        avgfid_1: 4,
        avginp_1: 152,
        avgcls_1: 0.727,
        rumshare_1: '1.612604346',
        url_1: 'https://www.adobe.com/acrobat/online/merge-pdf.html',
      },
      {
        url: 'Other',
        pageviews: '38797220',
        pageviews_1: '38700170',
        pageviews_diff: '97050',
        lcpgood: 71,
        fidgood: 92,
        inpgood: 82,
        clsgood: 64,
        lcpbad: 13,
        fidbad: 1,
        inpbad: 0,
        clsbad: 21,
        avglcp: 2656,
        avgfid: 10,
        avginp: 131,
        avgcls: 0.315,
        rumshare: '46.74867164',
        lcpgood_1: 70,
        fidgood_1: 90,
        inpgood_1: 80,
        clsgood_1: 56,
        lcpbad_1: 13,
        fidbad_1: 1,
        inpbad_1: 5,
        clsbad_1: 30,
        avglcp_1: 2533,
        avgfid_1: 9,
        avginp_1: 124,
        avgcls_1: 0.418,
        rumshare_1: '76.274825622',
        url_1: 'Other',
      },
    ],
    columns: [
      'url',
      'pageviews',
      'pageviews_1',
      'pageviews_diff',
      'lcpgood',
      'fidgood',
      'inpgood',
      'clsgood',
      'lcpbad',
      'fidbad',
      'inpbad',
      'clsbad',
      'avglcp',
      'avgfid',
      'avginp',
      'avgcls',
      'rumshare',
      'lcpgood_1',
      'fidgood_1',
      'inpgood_1',
      'clsgood_1',
      'lcpbad_1',
      'fidbad_1',
      'inpbad_1',
      'clsbad_1',
      'avglcp_1',
      'avgfid_1',
      'avginp_1',
      'avgcls_1',
      'rumshare_1',
      'url_1',
    ],
  },
  meta: {
    limit: 12,
    offset: 0,
    total: 12,
    columns: [
      'name',
      'value',
      'type',
    ],
    data: [
      {
        name: 'description',
        value: 'Get Helix RUM data for a given domain or owner/repo combination',
        type: 'query description',
      },
      {
        name: 'limit',
        value: 6,
        type: 'request parameter',
      },
      {
        name: 'interval',
        value: 30,
        type: 'request parameter',
      },
      {
        name: 'offset',
        value: 1,
        type: 'request parameter',
      },
      {
        name: 'startdate',
        value: '2022-02-01',
        type: 'request parameter',
      },
      {
        name: 'enddate',
        value: '2022-05-28',
        type: 'request parameter',
      },
      {
        name: 'timezone',
        value: 'UTC',
        type: 'request parameter',
      },
      {
        name: 'url',
        value: 'www.adobe.com/',
        type: 'request parameter',
      },
      {
        name: 'owner',
        value: '-',
        type: 'request parameter',
      },
      {
        name: 'repo',
        value: '-',
        type: 'request parameter',
      },
      {
        name: 'device',
        value: 'all',
        type: 'request parameter',
      },
      {
        name: 'rising',
        value: false,
        type: 'request parameter',
      },
      {
        name: 'avgcls',
        value: '75th percentile value of the Cumulative Layout Shift metric in the current period',
        type: 'response detail',
      },
      {
        name: 'avgcls_1',
        value: '75th percentile value of the CLS metric in the previous period',
        type: 'response detail',
      },
      {
        name: 'avgfid',
        value: '75th percentile value of the First Input Delay metric in milliseconds in the current period',
        type: 'response detail',
      },
      {
        name: 'avgfid_1',
        value: '75th percentile value of FID in the previous period',
        type: 'response detail',
      },
      {
        name: 'avginp',
        value: '75th percentile value of the Interaction to Next Paint metric in milliseconds in the current period',
        type: 'response detail',
      },
      {
        name: 'avginp_1',
        value: '75th percentile of INP in the previous period',
        type: 'response detail',
      },
      {
        name: 'avglcp',
        value: '75th percentile of the Largest Contentful Paint metric in milliseconds in the current period',
        type: 'response detail',
      },
      {
        name: 'avglcp_1',
        value: '75th percentile of LCP in the previous period',
        type: 'response detail',
      },
      {
        name: 'clsbad',
        value: 'percentage of all page views where Cumulative Layout Shift is in the “needs improvement” range in the current period',
        type: 'response detail',
      },
      {
        name: 'clsbad_1',
        value: 'percentage of of all page views with bad CLS in the previous period',
        type: 'response detail',
      },
      {
        name: 'clsgood',
        value: 'percentage of all page views where the CLS metric is in the “good” range in the current period',
        type: 'response detail',
      },
      {
        name: 'clsgood_1',
        value: 'percentage of pageviews with good CLS the the previous period',
        type: 'response detail',
      },
      {
        name: 'fidbad',
        value: 'percentage of pageviews with bad FID in the current period',
        type: 'response detail',
      },
      {
        name: 'fidbad_1',
        value: 'percentage of pageviews with bad FID in the previous period',
        type: 'response detail',
      },
      {
        name: 'fidgood',
        value: 'percentage of pageviews with good FID in the current period',
        type: 'response detail',
      },
      {
        name: 'fidgood_1',
        value: 'percentage of pageviews with good FID in the previous period',
        type: 'response detail',
      },
      {
        name: 'inpbad',
        value: 'percentage of pageviews with bad INP in the current period',
        type: 'response detail',
      },
      {
        name: 'inpbad_1',
        value: 'percentage of pageviews with bad INP in the previous period',
        type: 'response detail',
      },
      {
        name: 'inpgood',
        value: 'percentage of pageviews with good INP in the current period',
        type: 'response detail',
      },
      {
        name: 'inpgood_1',
        value: 'percentage of pageviews with bad INP in the previous period',
        type: 'response detail',
      },
      {
        name: 'lcpbad',
        value: 'percentage of pageviews with bad LCP in the current period',
        type: 'response detail',
      },
      {
        name: 'lcpbad_1',
        value: 'percentage of pageviews with bad LCP in the previous period',
        type: 'response detail',
      },
      {
        name: 'lcpgood',
        value: 'percentage of pageviews with good LCP in the current period',
        type: 'response detail',
      },
      {
        name: 'lcpgood_1',
        value: 'percentage of pageviews with good LCP in the current period',
        type: 'response detail',
      },
      {
        name: 'pageviews',
        value: 'estimated number of pageviews in the current period',
        type: 'response detail',
      },
      {
        name: 'pageviews_1',
        value: 'estimated number of pageviews in the previous period',
        type: 'response detail',
      },
      {
        name: 'pageviews_diff',
        value: 'difference in pageviews between the current and previous period. If the parameter rising is true, then pages will be ranked according to this value',
        type: 'response detail',
      },
      {
        name: 'rumshare',
        value: 'percentage of all traffic for the given domain that is going to this url in the current period',
        type: 'response detail',
      },
      {
        name: 'rumshare_1',
        value: 'percentage of of all traffic in the previous domain that is going to this url in the previous period',
        type: 'response detail',
      },
      {
        name: 'url',
        value: 'the URL of the page that is getting traffic',
        type: 'response detail',
      },
      {
        name: 'url_1',
        value: 'the URL of the page that is getting traffic in the previous period (these last two values are always the same)',
        type: 'response detail',
      },
    ],
  },
};
