AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SpacecatAuditWorkerFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: src/index-local.main
      Runtime: nodejs22.x
      CodeUri: .
      MemorySize: 6144
      Timeout: 900
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: !Ref AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: !Ref AWS_SECRET_ACCESS_KEY
          AWS_DEFAULT_REGION: !Ref AWS_DEFAULT_REGION
          GOOGLE_CLOUD_API_KEY: !Ref GOOGLE_CLOUD_API_KEY
          GOOGLE_CLIENT_ID: !Ref GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET: !Ref GOOGLE_CLIENT_SECRET
          GOOGLE_REDIRECT_URI: !Ref GOOGLE_REDIRECT_URI
          FIREFALL_API_KEY: !Ref FIREFALL_API_KEY
          FIREFALL_API_ENDPOINT: !Ref FIREFALL_API_ENDPOINT
          FIREFALL_IMS_ORG_ID: !Ref FIREFALL_IMS_ORG_ID
          FIREFALL_API_CAPABILITY_NAME: !Ref FIREFALL_API_CAPABILITY_NAME
          FIREFALL_MODEL: !Ref FIREFALL_MODEL
          S3_SCRAPER_BUCKET_NAME: !Ref S3_SCRAPER_BUCKET_NAME
          IMS_HOST: !Ref IMS_HOST
          IMS_CLIENT_ID: !Ref IMS_CLIENT_ID
          IMS_CLIENT_CODE: !Ref IMS_CLIENT_CODE
          IMS_CLIENT_SECRET: !Ref IMS_CLIENT_SECRET
          DYNAMO_TABLE_NAME_DATA: !Ref DYNAMO_TABLE_NAME_DATA
          QUEUE_SPACECAT_TO_MYSTIQUE: !Ref QUEUE_SPACECAT_TO_MYSTIQUE
          SHAREPOINT_AUTHORITY: !Ref SHAREPOINT_AUTHORITY
          SHAREPOINT_CLIENT_ID: !Ref SHAREPOINT_CLIENT_ID
          SHAREPOINT_CLIENT_SECRET: !Ref SHAREPOINT_CLIENT_SECRET
          SHAREPOINT_DOMAIN_ID: !Ref SHAREPOINT_DOMAIN_ID
          ADMIN_HLX_API_KEY: !Ref ADMIN_HLX_API_KEY
          SCRAPE_JOB_CONFIGURATION: !Ref SCRAPE_JOB_CONFIGURATION
          CONTENTAI_IMS_HOST: !Ref CONTENTAI_IMS_HOST
          CONTENTAI_CLIENT_ID: !Ref CONTENTAI_CLIENT_ID
          CONTENTAI_CLIENT_SECRET: !Ref CONTENTAI_CLIENT_SECRET
          CONTENTAI_CLIENT_SCOPE: !Ref CONTENTAI_CLIENT_SCOPE
          CONTENTAI_ENDPOINT: !Ref CONTENTAI_ENDPOINT
          S3_CONFIG_BUCKET: !Ref S3_CONFIG_BUCKET
          AZURE_OPENAI_ENDPOINT: !Ref AZURE_OPENAI_ENDPOINT
          AZURE_OPENAI_KEY: !Ref AZURE_OPENAI_KEY
          AZURE_API_VERSION: !Ref AZURE_API_VERSION
          AZURE_COMPLETION_DEPLOYMENT: !Ref AZURE_COMPLETION_DEPLOYMENT
          S3_MYSTIQUE_BUCKET_NAME: !Ref S3_MYSTIQUE_BUCKET_NAME
      Role: arn:aws:iam::682033462621:role/spacecat-role-lambda-generic
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Parameters:
  AWS_ACCESS_KEY_ID:
    Type: String
    Description: AWS Access Key ID
  AWS_SECRET_ACCESS_KEY:
    Type: String
    Description: AWS Secret Access Key
  AWS_DEFAULT_REGION:
    Type: String
    Description: AWS Default Region
    Default: us-east-1
  GOOGLE_CLOUD_API_KEY:
    Type: String
    Description: Google Cloud API Key
  GOOGLE_CLIENT_ID:
    Type: String
    Description: Google Client ID
  GOOGLE_CLIENT_SECRET:
    Type: String
    Description: Google Client Secret
  GOOGLE_REDIRECT_URI:
    Type: String
    Description: Google Redirect URI
  FIREFALL_API_KEY:
    Type: String
    Description: Firefall API Key
  FIREFALL_API_ENDPOINT:
    Type: String
    Description: Firefall API Endpoint
  FIREFALL_IMS_ORG_ID:
    Type: String
    Description: Firefall IMS Org ID
  FIREFALL_API_CAPABILITY_NAME:
    Type: String
    Description: Firefall API Capability Name
  FIREFALL_MODEL:
    Type: String
    Description: Firefall Model
  S3_SCRAPER_BUCKET_NAME:
    Type: String
    Description: S3 Scraper Bucket Name
  IMS_HOST:
    Type: String
    Description: IMS Host
  IMS_CLIENT_ID:
    Type: String
    Description: IMS Client ID
  IMS_CLIENT_CODE:
    Type: String
    Description: IMS Client Code
  IMS_CLIENT_SECRET:
    Type: String
    Description: IMS Client Secret
  DYNAMO_TABLE_NAME_DATA:
    Type: String
    Description: DynamoDB Table Name for Data
  QUEUE_SPACECAT_TO_MYSTIQUE:
    Type: String
    Description: Queue Name for Spacecat to Mystique
  SHAREPOINT_AUTHORITY:
    Type: String
    Description: Sharepoint Authority
  SHAREPOINT_CLIENT_ID:
    Type: String
    Description: Sharepoint Client ID
  SHAREPOINT_CLIENT_SECRET:
    Type: String
    Description: Sharepoint Client Secret
  SHAREPOINT_DOMAIN_ID:
    Type: String
    Description: Sharepoint Domain ID
  ADMIN_HLX_API_KEY:
    Type: String
    Description: Admin HLX API Key
  SCRAPE_JOB_CONFIGURATION:
    Type: String
    Description: Scrape job configuration JSON
  CONTENTAI_IMS_HOST:
    Type: String
    Description: ContentAI IMS Host
  CONTENTAI_CLIENT_ID:
    Type: String
    Description: ContentAI Client ID
  CONTENTAI_CLIENT_SECRET:
    Type: String
    Description: ContentAI Client Secret
  CONTENTAI_CLIENT_SCOPE:
    Type: String
    Description: ContentAI Client Scope
  CONTENTAI_ENDPOINT:
    Type: String
    Description: ContentAI Endpoint
  S3_CONFIG_BUCKET:
    Type: String
    Description: S3 Config Bucket Name
  AZURE_OPENAI_ENDPOINT:
    Type: String
    Description: Azure OpenAI Endpoint
  AZURE_OPENAI_KEY:
    Type: String
    Description: Azure OpenAI API Key
  AZURE_API_VERSION:
    Type: String
    Description: Azure API Version
  AZURE_COMPLETION_DEPLOYMENT:
    Type: String
    Description: Azure Completion Deployment Name
  S3_MYSTIQUE_BUCKET_NAME:
    Type: String
    Description: S3 Mystique Bucket Name
