/*
 * Copyright 2025 Adobe. All rights reserved.
 * This file is licensed to you under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License. You may obtain a copy
 * of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 * OF ANY KIND, either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

export default {
  'adobe.com': [
    '2026 Calendar',
    '3 D Content',
    '3d art',
    'AEM Forms  Connectors',
    'AEM Forms Fundamentals & Positioning',
    'AEM Workflow',
    'AI & Content Generation',
    'AI Animation',
    'AI Animation Generator',
    'AI Anime',
    'AI Anime Generator',
    'AI Architecture Prompts',
    'AI Art',
    'AI Art Generation',
    'AI Art Prompting',
    'AI Audio Translator',
    'AI Avatar',
    'AI Backgrounds for Product Photography',
    'AI Capabilities & Workspace',
    'AI Cartoon',
    'AI Cartoon generator',
    'AI Character',
    'AI Character Generator',
    'AI Content Tooling',
    'AI Document Assistant',
    'AI Drawing',
    'AI Dubbing',
    'AI Expand Photo',
    'AI Generative Expand',
    'AI Generative Recolor',
    'AI Generator',
    'AI Graffiti',
    'AI Graffiti Generator',
    'AI Graphic Design',
    'AI Image Generator',
    'AI Intelligence & Trust',
    'AI Music',
    'AI Music Generator',
    'AI Painting',
    'AI Painting Generator',
    'AI Photo Editor',
    'AI Photo Generator',
    'AI Picture Enhance',
    'AI Picture Generator',
    'AI Pixel Art Generator',
    'AI Portrait',
    'AI Prompts',
    'AI Resize Image',
    'AI Search Engines',
    'AI Search Success',
    'AI Sound Effect Generator',
    'AI Storyboard',
    'AI Tattoo',
    'AI Tattoo Design',
    'AI Tattoo Generator',
    'AI Text Effects',
    'AI Text To Image',
    'AI Text To Vector',
    'AI Text To Video',
    'AI Text to Video',
    'AI Video Editor',
    'AI Video Editor Free',
    'AI Video Generation',
    'AI Voice Generator',
    'AI Writer',
    'AI analytics',
    'AI art generator',
    'AI avatar generator',
    'AI character generator',
    'AI citation optimization',
    'AI comic',
    'AI image generator',
    'AI in Marketing (use cases + measurement for B2B)',
    'AI moodboard generator',
    'AI overviews',
    'AI portrait generator',
    'AI risk & workflow automation',
    'AI storyboard generator',
    'AI video editor',
    'AI video generator',
    'AI video translator',
    'AI visibility & citation measurement',
    'AI visibility tracking',
    'AX - Education & Student Use Cases',
    'AX - Extract PDF',
    'AX - Fill PDF',
    'AX - Insert PDF',
    'AX - Make PDF',
    'AX - Merge PDF',
    'AX - Open PDF',
    'AX - PDF editor - How To',
    'AX - PDF editor - Recommendation',
    'AX - PDF editor - Task Completion',
    'AX - PDF editor - Understanding',
    'AX - Persona-Driven Keyword',
    'AX - Print PDF',
    'AX - Productivity & Workflow Automation',
    'AX - Read PDF',
    'AX - Reduce PDF',
    'AX - Remove PDF',
    'AX - Rotate PDF',
    'AX - Scan PDF',
    'AX - Sign PDF',
    'AX - Summarize PDF',
    'AX - Templates & Content Generation',
    'AX - Translate PDF',
    'AX - View PDF',
    'Access entitlements & regional availability-CK',
    'Accessibility support & inclusive design-CK',
    'Account Management',
    'Acrobat Scanner App',
    'Acrobat Studio',
    'Acrobat Studio - CM Awareness',
    'Acrobat Studio - Case Studies',
    'Acrobat Studio - Competitor Comparison',
    'Acrobat Studio - Enterprise Pricing',
    'Acrobat Studio - Free Trial',
    'Acrobat Studio - Guidelines',
    'Acrobat Studio - How to Use',
    'Acrobat Studio - Individual Pricing',
    'Acrobat Studio - KPI',
    'Acrobat Studio - Plans',
    'Acrobat Studio - Procurement',
    'Acrobat Studio - Quality',
    'Acrobat Studio - ROI',
    'Acrobat Studio - Results Reporting',
    'Acrobat Studio - Reviews',
    'Acrobat Studio - Security',
    'Acrobat Studio - Team Deployment',
    'Acrobat Studio - Training',
    'Acrobat Studio - Troubleshooting',
    'Acrobat Studio - Use Cases',
    'Acrobat Studio for Enterprise',
    'Adaptive Forms',
    'Adaptive Forms Authoring',
    'Add Assets',
    'Add Audio',
    'Add Caption',
    'Add Certification to Your Resume - Acrobat',
    'Add Form to a web page',
    'Add Text on Photos',
    'Adding Images to PDFs',
    'Adjustment Layers',
    'Adobe Careers Overview',
    'Adobe Careers Role Focus',
    'Adobe Community Overview',
    'Adobe Experience Cloud Documentation',
    'Adobe Experience Manager',
    'Adobe Experience Manager Sites',
    'Adobe Forms',
    'Adobe Interview Process',
    'Adobe Sign',
    'Adoption & Awareness-CK',
    'Advanced GEO Topics',
    'Advertisement',
    'Afiliates',
    'Agency support & services',
    'Agentic AI fundamentals',
    'Agentic Marketing',
    'Agentic traffic analytics',
    'Ai Agents',
    'Ai Assistant',
    'Ai-Animation-Generator',
    'Ai-Anime-Generator',
    'Ai-Art-Generator',
    'Ai-Avatar-Generator',
    'Ai-Cartoon-Generator',
    'Ai-Character-Generator',
    'Ai-Comic-Generator',
    'Ai-Drawing-Generator',
    'Ai-Dubbing',
    'Ai-Face-Generator',
    'Ai-For-Game-Developers',
    'Ai-Graffiti-Generator',
    'Ai-Graphic-Design-Generator',
    'Ai-Music-Generator',
    'Ai-Painting-Generator',
    'Ai-Pet-Portrait-Generator',
    'Ai-Photo-Editor',
    'Ai-Portrait-Generator',
    'Ai-Sketch-Generator',
    'Ai-Video-Editor',
    'Ai-Video-Generator',
    'Alternative to Firefly -CK',
    'Alternatives / Comparisons-CK',
    'Animated Character',
    'Animation Maker',
    'Animation and Effects',
    'Another Topic',
    'Apply Process Overview',
    'Apply to Multiple Roles',
    'Applying to Multiple Roles',
    'Apprenticeships & Student Programs',
    'Architecture',
    'Asset Management',
    'Asset Renditions',
    'Asset Reporting',
    'Asset renditions',
    'Assets View',
    'Assets integrations',
    'Attaching Images and Files in Posts',
    'Audience Segment Comparisons-CK',
    'Avatar',
    'Background/Wallpaper',
    'Banner',
    'Batch PDF Generation',
    'Beginners vs Pros in the Community',
    'Benefits Comparison by Firm Size',
    'Benefits of Generative AI',
    'Best AI art generator',
    'Best AI dubbing',
    'Best AI dubbing tool',
    'Best AI image generator',
    'Best Of Behance',
    'Best Video Generator',
    'Best free AI art generator',
    'Best free AI image generator',
    'Best free Video Generator',
    'Best free video generator',
    'Best tools and platforms',
    'Blur Background',
    'Book',
    'Book Covers',
    'Brand Sentiment & Market Perception - CK',
    'Brand Understanding & Positioning - CK',
    'Brand Visibility',
    'Brand Visibility in Search',
    'Brand Voice Alignment - CK',
    'Brand consistency at scale',
    'Brand guidelines',
    'Brand safety & governance',
    'Brief-to-asset production',
    'Brochure',
    'Browsing Openings for Entry Level',
    'Brushes, Presets & Textures',
    'Bulk workflows in enterprise plans-CK',
    'Business & Education',
    'Business Card',
    'Business Flyer',
    'Buying conversion intent',
    'CRM & customer management',
    'CRM marketing & customer segmentation powered by customer relationship management (CRM) software + audience insights',
    'CV Creation',
    'CV Templates',
    'Calendar',
    'Campus Recruiting Program',
    'Can I trust it long-term? - safety & credibility-CK',
    'Can I use it for my work? - practical exploration-CK',
    'Cancellation',
    'Candidate Assessment Methods',
    'Captions',
    'Card/Invitation/Announcement',
    'Careers Application Process',
    'Careers Portal Differentiators',
    'Case Studies &  Proof',
    'Certificate',
    'Change Background',
    'Change PDF',
    'Change Video Speed',
    'Chart',
    'Chat with PDF',
    'Clip Maker',
    'Cloud-Native Forms Platform',
    'Coding Challenges in Interviews',
    'Collaboration & Group Work',
    'Collage',
    'Collage Maker',
    'Collages',
    'Collections',
    'Color & Tone',
    'Combine Image',
    'Combine PDF',
    'Comic Strips',
    'Commerce Support User Guide',
    'Commercial Safe AI',
    'Commercial use & output rights-CK',
    'Community Rules and Etiquette',
    'Community gallery & inspiration usage-CK',
    'Community vs Official Help Center',
    'Comparison / Evaluation',
    'Comparisons',
    'Competitive intelligence',
    'Compress PDF',
    'Compressing PDFs',
    'Configure Setting Preferences',
    'Content Hub',
    'Content Hub Documentation',
    'Content Management',
    'Content Scheduler',
    'Content Strategy',
    'Content Strategy2',
    'Content Supply Chain',
    'Content collaboration platform',
    'Content creation workflow',
    'Content optimization',
    'Content planning software',
    'Content production & landing page optimization',
    'Contract vs Full-time Gigs',
    'Conversational / Follow-Up',
    'Conversational commerce & integrations',
    'Convert Excel to PDF',
    'Convert Image Files',
    'Convert JPG to PDF',
    'Convert PDF',
    'Convert PDF to Excel',
    'Convert PDF to JPG',
    'Convert PDF to PNG',
    'Convert PDF to PPT',
    'Convert PDF to Word',
    'Convert PNG to PDF',
    'Convert PPT to PDF',
    'Convert Video',
    'Convert Word to PDF',
    'Convert image formats',
    'Converting from/to formats',
    'Core Make / Generate',
    'Cover',
    'Cover Letter Customization',
    'Cover Page',
    'Cover/Notice/Resignation Letter',
    'Create PDF',
    'Create a CV',
    'Creation and Production',
    'Creative Filters & Effects',
    'Creative Roles: Big vs Small',
    'Credits & Tokens - CK',
    'Crop Image',
    'Crop PDF',
    'Crop Video',
    'Cross product workflow',
    'Cross-LLM benchmarking',
    'Cross-Page',
    'Customer data foundations & analysis',
    'Data Audit Meta-Prompts - CK',
    'Data Audit Meta-Prompts-CK',
    'Data Chart',
    'Data Insights Audiences',
    'Data governance & master data',
    'Deadline Rescue/Panic/Instant Mode',
    'Definitions & Basics',
    'Delay/roll-out of features by region-CK',
    'Delete PDF',
    'Delivery and Activation',
    'Deployment & Architecture Options',
    'Design Creation',
    'Design Tool Exposure',
    'Designer Career Page Comparison',
    'Designer Salary Benchmark',
    'Different Acrobat versions',
    'Digital Signatures & E-Signing',
    'Direct Feature Comparisons-CK',
    'Diversity & Inclusion in Hiring',
    'DocuSign',
    'Document Automation',
    'Document Collaboration',
    'Document Generation & PDF Services',
    'Document Security',
    'Document of record',
    'Download and Installation',
    'Drawing',
    'Drawing & Illustration',
    'Dub Video',
    'Dub video with AI',
    'Dynamic Media',
    'Dynamic Media with OpenAPI',
    'E-Commence & Business Applications',
    'EPUB File Basics',
    'Ecommerce analytics & measurement',
    'Edit PDF',
    'Edit a pdf on mac - How To',
    'Edit a pdf on mac - Recommendation',
    'Edit a pdf on mac - Task Completion',
    'Edit a pdf on mac - Understanding',
    'Edit pdf - How To',
    'Edit pdf - Recommendation',
    'Edit pdf - Task Completion',
    'Edit pdf - Understanding',
    'Editable PDFs',
    'Education & Student Use Cases',
    'Education & Student Use Cases Acrobat',
    'Education & Student Use Cases Express',
    'Education Requirements in Tech',
    'Emerging Trends-CK',
    'Engineer Hiring Ease',
    'Engineering Interview Prep',
    'Enhance Image',
    'Enterprise AI solutions & adoption',
    'Enterprise CRM & System Integration',
    'Enterprise Forms',
    'Enterprise integrations',
    'Enterprise readiness & governance',
    'Enterprise usage tracking & metering-CK',
    'Enterprsie Forms',
    'Entity authority & data feeds',
    'Epubs',
    'Ethical & Responsible AI Representation - CK',
    'Exam Results Messages',
    'Experience League Events (Live & On-Demand)',
    'Experience Management Platform',
    'Experience Platform',
    'Experience Platform Documentation',
    'Export Settings',
    'Export, Output & File Management',
    'Extract Image',
    'Extract PDF',
    'Extract PDF Acrobat',
    'Extract PDF Express',
    'FAQs and recommended articles',
    'Fade In/Fade Out',
    'Favourite images & browser dependency issues-CK',
    'Feature & Capability Accuracy - CK',
    'Feature rollout & entitlement timing-CK',
    'Features - CK',
    'Fill & Sign',
    'Fill PDF',
    'Fill PDF Acrobat',
    'Fill PDF Express',
    'Finding Official Docs vs Q&A in the Community',
    'Firefly BLARE FEST 2026',
    'Firefly Credits',
    'Firefly Mobile App',
    'Firefly Outreach - Fav me',
    'Firefly vs NightCafe Comparison',
    'Flip/Rotate/Mirror Image',
    'Flyer',
    'Flyer Maker',
    'Form Data Integration',
    'Form Submissions',
    'Forms Analytics & Optimization',
    'Forms Designer',
    'Forms Security & Compliance',
    'Frames/Borders',
    'Free Features vs Premium',
    'Free Resume Templates',
    'Funeral Thank-You Messages',
    'Future trends',
    'Future-Proofing',
    'GDPR compliance for marketing: privacy-safe data collection & activation',
    'GIF Maker',
    'GenAI for Marketing',
    'General GEO tools',
    'General Generative Engine Optimization tools',
    'General Prompt',
    'General Question',
    'Generate AI art',
    'Generate AI art for free',
    'Generate Commercial Safe AI',
    'Generate Image',
    'Generate Image Free',
    'Generate Video',
    'Generate image with AI',
    'Generate image with AI for Free',
    'Generate video',
    'Generate video with AI',
    'Generate video with AI for free',
    'Generative AI Benefits',
    'Generative AI for PDFs',
    'Generative AI/Content Creation',
    'Generative Sound Effects',
    'Generative-Match',
    'Generic',
    'Generic AI has no brand memory',
    'Generic QUestion',
    'Getting Started',
    'Getting Started in the Community',
    'Gif Maker',
    'Goodbye Message Ideas',
    'Google Docs to PDF',
    'Google doc to PDF',
    'Google reCAPTCHA',
    'Growth for Junior Designers',
    "Guidelines that don't go far enough",
    'HIPAA',
    'Happiness Quotes',
    'Headless Forms',
    'Heic to jpg',
    'Heic to pdf',
    'Help documentation',
    'Hiring Timeline & Feedback',
    'Hiring Timeline Transparency',
    'Holiday Card',
    'Hoodie Design',
    'How to Search in the Community',
    'How to Write a Resume - Acrobat',
    'How to create a logo',
    'How to create a marketing plan',
    'How to create a presentation',
    'How to write a business plan',
    'How-To',
    'IRS-W9 Form',
    'ISWA',
    'Illustartion and Drawing',
    'Image Cropper',
    'Image Editor',
    'Image Generator (Text to Image)',
    'Image Resizer',
    'Image Style Transfer',
    'Image Style Transfer AI',
    'Image To AI Video',
    'Image to AI Video',
    'Image to Gif',
    'Image to Image',
    'Image to Video',
    'Image to video AI',
    'Image-To-Image',
    'Image-To-Video',
    'Image-to-Image AI',
    'Image-to-Video Transformation',
    'Image-to-image AI',
    'In-Demand Skills',
    'Indemnification for enterprise users-CK',
    'Industry - Manufacturing',
    'Industry Trends',
    'Infographic',
    'Infographics',
    'Insert PDF',
    'Insert PDF Acrobat',
    'Insert PDF Express',
    'Insert PDF Pages',
    'Installation & Setup',
    'Institutional memory at risk',
    'Integrations & data stack',
    'International / Multilingual',
    'Internship Conversion Rates',
    'Internship Interview Timeline',
    'Internships & New Grad Benefits',
    'Interview Timeline',
    'Invoice',
    'Invoice Generator',
    'Job Alerts & Subscriptions',
    'Job Alerts Availability',
    'Journal',
    'Keyboard Shortcuts',
    'Kindle to PDF',
    'Kindle to PDF Conversion',
    'LLM019 Long-Form Expansion',
    'Label',
    'Languages & Accessibility',
    'Layers, Masks & Smart Objects',
    'Learning Home / Training Options',
    'Letter',
    'Letterhead',
    'Licensing & model updates for enterprise-CK',
    'Logo',
    'Logo Maker',
    'Logos',
    'MOV to MP4',
    'MP4 To GIF',
    'Make PDF',
    'Make PDF Acrobat',
    'Make PDF Express',
    'Managing notifications and follows',
    'Map',
    'Marketing Automation',
    'Marketing automation',
    'Maze',
    'Meme',
    'Meme Generator',
    'Menu',
    'Merge PDF',
    'Merge PDF Acrobat',
    'Merge PDF Express',
    'Merge Video',
    'Metadata Management',
    'Metrics & Analytics',
    'Miscellaneous / Others Intents',
    'Misconception Testing - CK',
    'Mobile App',
    'Mobile Apply Experience',
    'Mobile Video Editor - Commercial',
    'Mobile Video Editor - Informational',
    'Mobile vs desktop capability parity-CK',
    'Model-training data & user content-CK',
    'Mood Board',
    'Mood Board - Design Ideation - Commercial',
    'Mood Board - Design Ideation - Informational',
    'Mood Board - Informational',
    'Mood Board - Storyboard - Commercial',
    'Mood Board - Storyboard - Informational',
    'Mood Board - Video Ideation - Commercial',
    'Mood Board - Video Ideation - Informational',
    'Mood Boards',
    'Moodboard',
    'Multi-media/asset pipelines (video, audio, image)-CK',
    'Nature',
    'Negatives',
    'Networking with Recruiters',
    'New',
    'New Grad Pros & Cons',
    'Newest Topic',
    'Newsletter',
    'Newsletter Email',
    'Niche Applications',
    'No way to pressure-test creative early',
    'Number PDF Pages',
    'OCR PDF',
    'Onboarding Guide / Perspectives',
    'Onboarding complexity is a real commitment',
    'Open PDF',
    'Open PDF Acrobat',
    'Open PDF Express',
    'Optical Character Recognition (OCR)',
    'Output Quality / Features',
    'Output uniqueness & exclusivity-CK',
    'Overall Comparative Perception-CK',
    'PDF AI',
    'PDF Conversion',
    'PDF Encryption',
    'PDF Format Conversion',
    'PDF Generation',
    'PDF Greyscale Conversion',
    'PDF Protection',
    'PDF Reader',
    'PDF Translation',
    'PDF editor - How To',
    'PDF editor - How To Acrobat',
    'PDF editor - How To Express',
    'PDF editor - Recommendation',
    'PDF editor - Recommendation Acrobat',
    'PDF editor - Recommendation Express',
    'PDF editor - Task Completion',
    'PDF editor - Task Completion Acrobat',
    'PDF editor - Task Completion Express',
    'PDF editor - Understanding',
    'PDF editor - Understanding Acrobat',
    'PDF editor - Understanding Express',
    'PDF to greyscale',
    'PNG Maker',
    'PNG to JPG',
    'PNG to SVG',
    'Painting, Drawing and Brushes',
    'Partner Models',
    'Perception Gaps / Criticism-CK',
    'Performance marketing fundamentals',
    'Permission Management',
    'Persona-Driven Keyword',
    'Persona-Driven Keyword Acrobat',
    'Persona-Driven Keyword Express',
    'Photo Editing',
    'Photo Editor',
    'Photo Effects',
    'Photo Filter',
    'Photo editing features',
    'Pixel Art',
    'Planner/Schedule',
    'Plans & Pricing - CK',
    'Playlists (video collections)',
    'Portfolio',
    'Portfolio Review Prep',
    'Poster',
    'Poster Maker',
    'Poster ideas',
    'Posters',
    'Posting a Question',
    'Presentation',
    'Presentation Maker',
    'Pricing & Plans',
    'Pricing / Access-CK',
    'Print Design',
    'Print PDF',
    'Print PDF Acrobat',
    'Print PDF Express',
    'Producivity Automation',
    'Product Announcements',
    'Product Manager Interview Questions',
    'Productivity & Workflow Automation',
    'Productivity & Workflow Automation Acrobat',
    'Productivity & Workflow Automation Express',
    'Profile Picture',
    'Program',
    'Programmatic',
    'Prom Poster',
    'Prompt intelligence',
    'Prompt monitoring & testing',
    'Prompt seed reproducibility-CK',
    'Prompt translation & language accuracy-CK',
    'Proposal',
    'Protect PDF',
    'QR Code',
    'QR Code Scanning',
    'QR Code Scanning with Acrobat',
    'QR Codes',
    'Read PDF',
    'Read PDF Acrobat',
    'Read PDF Express',
    'Recolor Image',
    'Recruiter Tools & Outreach',
    'Reduce PDF',
    'Reduce PDF Acrobat',
    'Reduce PDF Express',
    'Release updates & New Features',
    'Remote Work Availability',
    'Remote vs On-site Roles',
    'Remote-Friendly Roles Check',
    'Remote-friendly Roles for New Grads',
    'Remove Audio',
    'Remove Background',
    'Remove Object From Photo',
    'Remove PDF',
    'Remove PDF Acrobat',
    'Remove PDF Express',
    'Rendering & crawlability',
    'Reorder Pages',
    'Repair PDF',
    'Repairing Broken PDFs',
    'Report',
    'Reporting & ROI',
    'Reporting & governance',
    'Reporting Spam & Harassment',
    'Reporting and Insights',
    'Request E-Sign',
    'Required Application Documents',
    'Resize Image',
    'Resize Video',
    'Resume',
    'Resume Builder',
    'Resume Tailoring for Design Roles',
    'Retouching, Remove & Filters (incl. AI)',
    'Review cycles slowing everything down',
    'Rights Management',
    'Rotate PDF',
    'Rotate PDF Acrobat',
    'Rotate PDF Express',
    'Rotate Video',
    'SEO Hub',
    'SWOT Analysis Templates',
    'Scan PDF',
    'Scan PDF Acrobat',
    'Scan PDF Express',
    'Scene to Image',
    'Scene-To-Image',
    'Screenshot',
    'Search Assets',
    'Segmentation & product discovery',
    'Selections, Transform & Resize',
    'Sentiment-Driven Curiosity - inspired by user feedback-CK',
    'Shapes, paths and vector tools',
    'Shared device license limitations-CK',
    'Should I switch or invest? - evaluation & comparison-CK',
    'Sign PDF',
    'Sign PDF Acrobat',
    'Sign PDF Express',
    'Sign PDF/Electronic-signature/e-sign/Digital Signature',
    'Signing & filling forms',
    'Sketch to image AI',
    'Sketch-To-Image',
    'Sketch-to-Image AI',
    'Smart Imaging',
    'Smart Tags',
    'Socia Media',
    'Social Post',
    'Social Story',
    'Sound Effects',
    'Sound-Effect-Generator',
    'Source & Information Traceability - CK',
    'Split PDF',
    'Split PDF Acrobat',
    'Split PDF Express',
    'Split Video',
    'Spreadsheet files',
    'Sticker',
    'Strategic Outlook / Future Direction-CK',
    'Student Job Search Starter',
    'Study Optimization & Productivity',
    'Summarize PDF',
    'Summarize PDF Acrobat',
    'Summarize PDF Express',
    'Summary Generator',
    'System Compatibility/Requirements',
    'System Requirements',
    'T-Shirt Design',
    'Tattoo Generator',
    'Teacher Appreciation',
    'Tech SEO PDF Test',
    'Technical GEO & crawler access',
    'Technical Generative Engine Optimization & crawler access',
    'Technical SEO Crossover',
    'Template Generation',
    'Templates & Content Generation',
    'Templates & Content Generation Acrobat',
    'Templates & Content Generation Express',
    'Templates & guides for productivity',
    'Temporal / Trend Comparisons-CK',
    'Text & Design Effects',
    'Text & Typography',
    'Text Animation',
    'Text Effects',
    'Text to Speech',
    'Text to Speech AI',
    'Text-To-Image',
    'Text-To-Speech',
    'Text-to-Image Generation',
    'Thumbnail',
    'Ticket',
    'TikTok Followers',
    'TikTok Views',
    'Timeline',
    'Tools & Platforms',
    'Tracking Your Application',
    'Translate Audio',
    'Translate PDF',
    'Translate PDF Acrobat',
    'Translate PDF Express',
    'Translate Spanish',
    'Translate Video',
    'Translate-Audio',
    'Translate-Video',
    'Transparent Background Maker',
    'Travel Brochure',
    'Trending Topics in the Community',
    'Trim Video',
    'Troubleshooting/Error Resolution',
    'Troubleshooting/Pain Points',
    'Trust, Authenticity & Brand Safety-CK',
    'Unblur/Deblur Image',
    'Understanding & Concept Clarity',
    'Understanding different document/file types compatible with Acroba',
    'Uninstall and Troubleshooting',
    'Unlock PDF',
    'Unlock PDF with Acrobat',
    'Upload format & file type constraints-CK',
    'Upscale Image / AI Upscale',
    'Use Case-Specific',
    'Use Case-Based Comparisons-CK',
    'User Experience',
    'Value for Beginners vs Pros',
    'Vendor selection & procurement',
    'Vertical videos',
    'Video Content Type',
    'Video Creation',
    'Video Editing',
    'Video Editor',
    'Video Generator (Text to Video)',
    'Video Trimmer',
    'Video and animation',
    'Video generation feature constraints-CK',
    'Video templates',
    'View PDF',
    'View PDF Acrobat',
    'View PDF Express',
    'Viewing, editing, creating PDFs',
    'Voice & Conversion AI',
    'Voiceover',
    'Wallpaper',
    'Web Page',
    'Webp Import',
    'Wedding Banner',
    'Wedding ideas',
    'What You Can Do in the Community',
    'What is AI Art',
    'What is this, really? - discovery curiosity-CK',
    'Work Flexibility in Tech',
    'Workflow Automation',
    'Workflow Automation & BPM',
    'Workflow and Planning',
    'Workflow, Productivity & Customization',
    'Worksheet',
    'Writing & Structuring Help',
    'XFA based PDF Forms',
    'XLSX File Basics',
    'XML Files',
    'Yet another Topic',
    'a4 format',
    'abode sign in',
    'acrobat premium',
    'acrobat writer',
    'acronat',
    'add assets aem',
    'add page numbers to pdf',
    'add pages to pdf',
    'adobe',
    'adobe acrobat online',
    'adobe analytics',
    'adobe analytics seo',
    'adobe character animator',
    'adobe creative cloud',
    'adobe dam integration',
    'adobe dam integration figma',
    'adobe dam integration workfront',
    'adobe digital asset management',
    'adobe digital asset manager',
    'adobe document cloud',
    'adobe dynamic media',
    'adobe edge',
    'adobe express',
    'adobe fire fly',
    'adobe images',
    'adobe lightroom',
    'adobe portfolio',
    'adobe pro login',
    'adobe scan login',
    'adobe sitecatalyst',
    'adobe spark',
    'adobe spark page',
    'adobe spark post',
    'adobe spark video',
    'adobe stock photos',
    'adobe workfront',
    'adobedtm.com',
    'aem assets AI features',
    'aem developer',
    'aem digital asset management',
    'ai generated art',
    'ai generated images',
    'ai generated photos',
    'ai generated pictures',
    'ai image generation tools',
    'ai image generator',
    'ai image generator from image',
    'ai images',
    'ai pdf reader',
    'ai photo',
    'ai photos',
    'ai picture generator',
    'ai pictures',
    'ancient greece social structure',
    'anime eyes',
    'api 2023',
    'api for images',
    'api imaging',
    'api services',
    'asset management reports',
    'asset metadata and alt tags',
    'assets prime',
    'assets ultimate',
    'assets.adobedtm.com',
    'audience analytics',
    'audience manager',
    'bad elf on the shelf',
    'behance',
    'best ai image generator',
    'best pdf editor',
    'big boobs',
    'big tits',
    'border-top',
    'brand design',
    'branding',
    'branding services',
    'canonical hreflang',
    'carmen winstead',
    'character animator',
    'chat pdf',
    'christmas clipart',
    'color tags',
    'combine pdf',
    'combine pdf files',
    'combine pdfs',
    'combine pdfs into one',
    'combine two pdfs',
    'commerce frontend development',
    'compress pdf',
    'content hub',
    'convert file to pdf',
    'convert image to pdf',
    'convert jpeg to pdf',
    'convert jpg to pdf',
    'convert pdf to ai',
    'convert pdf to doc',
    'convert pdf to excel',
    'convert pdf to image',
    'convert pdf to jpg',
    'convert pdf to jpg free',
    'convert pdf to powerpoint',
    'convert pdf to ppt',
    'convert pdf to word',
    'convert pdf to word free',
    'convert to pdf',
    'convert word to pdf',
    'converting pdf to word',
    'cool wallpapers',
    'cover letter',
    'create ai images',
    'create pdf from images',
    'create plugin',
    'crop image',
    'crop pdf',
    'customer ai',
    'customer journey analytics',
    'cv template',
    'dam solutions',
    'dam vendors',
    'data-sly-include',
    'data-sly-unwrap',
    'derek cha',
    'design portfolio',
    'developer tools APIs SDKs',
    'dfwea',
    'dock manifest',
    'document generation word',
    'document workflow automation',
    'docx to pdf',
    'dynamic media open apis',
    'eastern woodlands clothing',
    'eastern woodlands transportation',
    'ecid',
    'edit pdf',
    'edit pdf free',
    'embed video sdk',
    'esign',
    'evars',
    'event app builder',
    'excel to pdf',
    'experience manager',
    'experience platform',
    'extensibility',
    'extract pages from pdf',
    'extract text from image',
    'firefly',
    'firefly 2 adobe',
    'firefly ai',
    'flyer templates',
    'flyout menu',
    'formdata',
    'formdata file',
    'fortnite channel art',
    'free ai generator',
    'free ai photo generator',
    'free ai picture generator',
    'free ai video generator',
    'free font',
    'free jpg to pdf converter',
    'free pdf compressor',
    'free pdf converter',
    'free pdf editor',
    'free pdf editor download',
    'free pdf merger',
    'free pdf to jpg converter',
    'free pdf to word converter',
    'free photo editor',
    'free portfolio sites',
    'free resume templates',
    'free video editor',
    'freelance',
    'funny pictures',
    'generate PDF from template',
    'generative ai',
    'generative ai video',
    'generative match',
    'get credentials',
    'get-credentials',
    'graphic design',
    'graphic design examples',
    'graphic design portfolio',
    'graphic design projects',
    'grunge texture',
    'happy halloween',
    'happy halloween images',
    'happy mothers day',
    'happy mothers day images',
    'happy thanksgiving images',
    'hatchet chapter 5',
    'hatchet chapter 6',
    'heic to jpg',
    'how to calculate engagement rate',
    'how to combine pdf files',
    'how to compress a pdf',
    'how to convert a pdf to word',
    'how to convert jpg to pdf',
    'how to convert pdf to jpg',
    'how to convert pdf to word',
    'how to create a plugin',
    'how to create ai videos',
    'how to create invoices',
    'how to edit a pdf',
    'how to edit pdf',
    'how to make a pdf smaller',
    'how to make a plugin',
    'how to make ai video',
    'how to make ai videos',
    'how to make plugins',
    'how to merge pdf files',
    'how to reduce pdf file size',
    'hreflang sitemap',
    'htmlelement',
    'image to text',
    'intelligent document processing',
    'invoice template',
    "jack o'lantern faces",
    'java pdf api',
    'javax.jcr.node',
    'journey orchestration',
    'jpg to pdf',
    'june calendar 2024',
    'kansas state animal',
    'kansas state bird and flower',
    'kansas symbols',
    'kathleen nimmo lynch',
    'keyword unavailable',
    'kinetic engineer',
    'labs',
    'lightroom',
    'linearized pdf',
    'logo design',
    'magento 2 development',
    'magento developer',
    'magento developers',
    'magento extension developer',
    'magento extensions development',
    'magento integration',
    'magento news',
    'make pdf smaller',
    'making documents accessible to people with disabilities',
    'manifest png',
    'marketo certification',
    "mcdonald's photos",
    'media library',
    'merge pdf files',
    'merge pdf free',
    'merge pdfs',
    'metadata management strategy',
    'modern warfare thumbnail',
    'mov to mp4',
    'mr beast thumbnail',
    'my pdf',
    'new vs returning visitors',
    'new year wishes',
    'old grannies',
    'online tools',
    'organize digital assets',
    'packaging design',
    'page builder',
    'pages to word',
    'paid search analysis',
    'paid search analytics',
    'paper texture',
    'password protect pdf',
    'pdf',
    'pdf a word',
    'pdf account',
    'pdf combiner',
    'pdf editor',
    'pdf editor free',
    'pdf editor free download',
    'pdf editor login',
    'pdf log in',
    'pdf login',
    'pdf login account',
    'pdf page remover',
    'pdf reader',
    'pdf seo',
    'pdf sign in',
    'pdf signing',
    'pdf simple login',
    'pdf to excel',
    'pdf to jpeg',
    'pdf to jpg',
    'pdf to jpg converter',
    'pdf to png',
    'pdf to powerpoint',
    'pdf to powerpoint converter',
    'pdf to ppt',
    'pdf to word',
    'pdf to word converter',
    'pdf to word doc',
    'pdf to word document',
    'photo editor',
    'photoshop',
    'photoshop download',
    'photoshop plug-in natural',
    'picture to pdf',
    'pin page',
    'plugin-hybrider',
    'png',
    'png to jpg',
    'png to pdf',
    'png to svg converter',
    'png to vector',
    'ppt',
    'product recommendation',
    'productivity automation',
    'project editor',
    'pwa',
    'qr code generator',
    'rearrange pdf pages',
    'reduce pdf size',
    'refering url',
    'relational schema',
    'remove background from image free',
    'resize pdf',
    'rest api',
    'resume',
    'resume templates',
    'rotate pdf',
    'save options',
    'scanner',
    'sdk initialization',
    'server to server authentication',
    'services api',
    'shadowroot',
    'share plugin',
    'shortened cake examples',
    'shrink pdf',
    'sign and fill',
    'sign request',
    'signature',
    'site search solutions',
    'sketch to ai art',
    'sketch to image',
    'skull drawing',
    'smart tags',
    'spark page',
    'spark video',
    'sparkadobe',
    'split pdf',
    'state animals of kansas',
    'stock api',
    'success message ux',
    'summarizer',
    'test again',
    'test topic',
    'thanksgiving background',
    'thanksgiving wallpaper',
    'topic 2 under c3',
    'topic under c3',
    'transparent background',
    'transparent image',
    'transparent png',
    'unlock pdf',
    'vanity urls',
    'view pdf',
    'vtuber model',
    'websdk',
    'website design',
    'website portfolio',
    'what is a linearized pdf',
    'what is a shortened cake',
    'what is a solid color',
    'what is an adobe',
    'what is linearized pdf',
    'what is solid color',
    'why homework should not be banned',
    'word doc to pdf',
    'word to pdf',
    'workflow automation',
    'workfront careers',
  ],
  'lovesac.com': [
    'Adult Bean Bag Options',
    'Bean Bag Availability',
    'Bean Bag Bed Choices',
    'Bean Bag Chairs for Kids',
    'Bean Bag Couch Options',
    'Bean Bag Selection',
    'Brand',
    'Comparison',
    'Configuration & Fit',
    'Couches for Sale Nearby',
    'Custom Sectional Options',
    'Durability & Care',
    'Durability of Lovesac Materials',
    'Fabric & Material Choices',
    'Features & Options',
    'Footsac & Blanket Products',
    'Home theater sound and charging systems',
    'Life Stage & Use Case',
    'Living Room Furniture Ideas',
    'Lovesac Accessories and Instructions',
    'Lovesac Bean Bag Chair Styles',
    'Lovesac Bean Bag Products',
    'Lovesac Chair Options',
    'Lovesac Configuration Ideas',
    'Lovesac Customer Support',
    'Lovesac Deals & Promotions',
    'Lovesac Furniture Overview',
    'Lovesac Ottoman Variants',
    'Lovesac Policies and Financing',
    'Lovesac Sectional Insights',
    'Lovesac Snugg Features',
    'Modular Design Benefits',
    'Modular Sectional Options',
    'Modular furniture configurations',
    'Oversized Bean Bags',
    'Pillowsac Products',
    'Premium Modular Furniture',
    'Pricing & Value',
    'Product',
    'Product Selection',
    'Recliner & Reclining Discovery',
    'Sactionals Cover Options',
    'Space-Saving Solutions',
    'Support & Purchase',
    'bean bag chairs',
    'bean bag chairs for adults',
    'beanbag chair',
    'best bean bag chair',
    'love sac',
    'lovesac',
    'lovesac couch',
    'modular sectional sofa',
    'sectionals',
    'small sectional couch',
  ],
};
